# Generated by Django 5.0.3 on 2024-03-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_stakeholdermessageadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StakeholderMessageAdmin',
        ),
    ]
